package com.exam;
// Generated Jun 13, 2018 11:43:00 AM by Hibernate Tools 4.3.1

import org.hibernate.validator.constraints.NotEmpty;




/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {

    
     private String customerId;
     @NotEmpty
     private String name;
      @NotEmpty
     private String companyName;
      @NotEmpty
     private String phone;
     private Integer receivable;

    public Customer() {
    }

	
    public Customer(String customerId) {
        this.customerId = customerId;
    }
    public Customer(String customerId, String name, String companyName, String phone, Integer receivable) {
       this.customerId = customerId;
       this.name = name;
       this.companyName = companyName;
       this.phone = phone;
       this.receivable = receivable;
    }
   
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Integer getReceivable() {
        return this.receivable;
    }
    
    public void setReceivable(Integer receivable) {
        this.receivable = receivable;
    }




}


