package com.exam;
// Generated Jun 13, 2018 11:43:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Purchase generated by hbm2java
 */
public class Purchase  implements java.io.Serializable {


     private String purchaseId;
     private String transactionId;
     private String supplierId;
     private String productId;
     private String productName;
     private String model;
     private String brand;
     private Integer quantity;
     private Integer costPerUnit;
     private Integer totalCostPrice;
     private Integer transportCost;
     private Integer otherCost;
     private Integer totalProductCost;
     private Integer payment;
     private Integer payable;
     private Date date;

    public Purchase() {
    }

	
    public Purchase(String purchaseId) {
        this.purchaseId = purchaseId;
    }
    public Purchase(String purchaseId, String transactionId, String supplierId, String productId, String productName, String model, String brand, Integer quantity, Integer costPerUnit, Integer totalCostPrice, Integer transportCost, Integer otherCost, Integer totalProductCost, Integer payment, Integer payable, Date date) {
       this.purchaseId = purchaseId;
       this.transactionId = transactionId;
       this.supplierId = supplierId;
       this.productId = productId;
       this.productName = productName;
       this.model = model;
       this.brand = brand;
       this.quantity = quantity;
       this.costPerUnit = costPerUnit;
       this.totalCostPrice = totalCostPrice;
       this.transportCost = transportCost;
       this.otherCost = otherCost;
       this.totalProductCost = totalProductCost;
       this.payment = payment;
       this.payable = payable;
       this.date = date;
    }
   
    public String getPurchaseId() {
        return this.purchaseId;
    }
    
    public void setPurchaseId(String purchaseId) {
        this.purchaseId = purchaseId;
    }
    public String getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }
    public String getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getCostPerUnit() {
        return this.costPerUnit;
    }
    
    public void setCostPerUnit(Integer costPerUnit) {
        this.costPerUnit = costPerUnit;
    }
    public Integer getTotalCostPrice() {
        return this.totalCostPrice;
    }
    
    public void setTotalCostPrice(Integer totalCostPrice) {
        this.totalCostPrice = totalCostPrice;
    }
    public Integer getTransportCost() {
        return this.transportCost;
    }
    
    public void setTransportCost(Integer transportCost) {
        this.transportCost = transportCost;
    }
    public Integer getOtherCost() {
        return this.otherCost;
    }
    
    public void setOtherCost(Integer otherCost) {
        this.otherCost = otherCost;
    }
    public Integer getTotalProductCost() {
        return this.totalProductCost;
    }
    
    public void setTotalProductCost(Integer totalProductCost) {
        this.totalProductCost = totalProductCost;
    }
    public Integer getPayment() {
        return this.payment;
    }
    
    public void setPayment(Integer payment) {
        this.payment = payment;
    }
    public Integer getPayable() {
        return this.payable;
    }
    
    public void setPayable(Integer payable) {
        this.payable = payable;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }


private int salesPerUnit;

    public int getSalesPerUnit() {
        return salesPerUnit;
    }

    public void setSalesPerUnit(int salesPerUnit) {
        this.salesPerUnit = salesPerUnit;
    }


}


