package com.exam;
// Generated Jun 13, 2018 11:43:00 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private String transactionId;
     private Integer amount;
     private String type;
     private Date date;
     private Integer cash;
     private Integer nonCash;

    public Transaction() {
    }

	
    public Transaction(String transactionId) {
        this.transactionId = transactionId;
    }
    public Transaction(String transactionId, Integer amount, String type, Date date) {
       this.transactionId = transactionId;
       this.amount = amount;
       this.type = type;
       this.date = date;
    }
   
    public String getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    public Integer getCash() {
        return cash;
    }

    public void setCash(Integer cash) {
        this.cash = cash;
    }

    public Integer getNonCash() {
        return nonCash;
    }

    public void setNonCash(Integer nonCash) {
        this.nonCash = nonCash;
    }

    


}


