package com.exam;
// Generated Jun 13, 2018 11:43:00 AM by Hibernate Tools 4.3.1

import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotEmpty;




/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {

     //@NotEmpty
     //@Size(min = 6,max = 8)
     private String id;
    // @NotEmpty
     //@Size(min = 6,max = 15)
     private String name;
    // @NotEmpty
    // @Pattern(regexp="[a-zA-Z]+[a-zA-Z0-9]+[@]+[a-zA-Z]+[.]+[a-zA-Z]{2,3}$",message = "Hints:Idb657@gmail.com")
     private String email;
    // @NotEmpty
      //@Pattern(regexp="[a-zA-Z]+[a-zA-Z0-9]{8,10}$",message = "Password should be alphanumeric character and minimum 8 character")
     private String password;

    public User() {
    }

	
    public User(String id) {
        this.id = id;
    }
    public User(String id, String name, String email, String password) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.password = password;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


